export const environment = {
  prod: true,
  API_URI: "API_URI_PLACEHOLDER",
  SECRET_KEY: "SECRET_KEY_PLACEHOLDER",
  GOOGLE_MAPS_API_KEY: "MAPS_KEY_PLACEHOLDER",
  SOCKET_URI: "SOCKET_URI_PLACEHOLDER"
};